name: "Podcast Generator by Joel del Castillo"
author: "Joel del Castillo"
description: "Generates a feed for a podcast from a YAML file"
runs: 
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The committer's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}
